name: Playright Tests

on: 
  pull_request:
  schedule:
    - cron: '50 3 * * *' # Runs every day at midnight
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to run specific tests'
        required: true
        default: '@smoke'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests
        if: github.event_name == 'pull_request'
        run: npx playwright test --grep "@smoke" --reporter=html

      - name: Run Regression Tests
        if: github.event_name == 'schedule'
        run: npx playwright test --grep "@regression" --reporter=html

      - name: Upload Playright test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: test-results/

      - name: Upload Playwright Html report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-html-report
          path: playwright-report

      - name: Deploy Playwright report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages